import Queue from 'bull';
import { env } from '../config/env';
import { logger } from '../config/logger';
import prisma from '../config/database';
import { groupService } from '../services/group.service';


export const syncQueue = new Queue('offline-sync', env.REDIS_URL, {
  redis: { maxRetriesPerRequest: null },
  defaultJobOptions: {
    attempts: 5, // It will try a maximum of 5 times
    backoff: {
      type: 'exponential',
      delay: 2000, // Waits 2s, then 4s, then 8s, then 16s before final attempt
    },
    removeOnComplete: true, // Keep Redis clean by deleting successful jobs
  }
});

syncQueue.process(async (job) => {
  // offlineId is the UUID generated by SQLite on the mobile app!
  const { userId, groupId, amount, offlineId } = job.data;

  try {
    // 1. ⭐️ IDEMPOTENCY CHECK (Prevent Double Charging!)
    // We use the offlineId from the phone to ensure we haven't already processed this exact tap.
    const referenceBase = `SYNC_${offlineId}`;
    const existingTx = await prisma.transaction.findFirst({
      where: { reference: `${referenceBase}_DEBIT` }
    });

    if (existingTx) {
      logger.info({ offlineId }, 'Offline contribution already synced. Skipping.');
      return;
    }

    // 2. Fetch Wallet & Group Data
    const group = await prisma.group.findUnique({
      where: { id: groupId },
      include: { wallet: true },
    });
    const userWallet = await prisma.wallet.findUnique({ where: { userId } });
    const user = await prisma.user.findUnique({ where: { id: userId } });

    if (!group || !group.wallet || !userWallet) throw new Error('Missing wallet/group data');
    if (userWallet.balance < amount) throw new Error('Insufficient funds for offline sync');

    // 3. Massive Atomic Transaction (Exactly like Day 24, but with our Idempotent Reference)
    await prisma.$transaction(async (tx) => {
      // Deduct User
      await tx.wallet.update({ where: { id: userWallet.id }, data: { balance: { decrement: amount } } });
      // Record User Debit
      await tx.transaction.create({
        data: { walletId: userWallet.id, amount, type: 'CONTRIBUTION', status: 'SUCCESS', reference: `${referenceBase}_DEBIT`, description: `Offline Sync: Contribution to ${group.name}` }
      });
      // Credit Group
      await tx.wallet.update({ where: { id: group.wallet!.id }, data: { balance: { increment: amount } } });
      // Record Group Credit
      await tx.transaction.create({
        data: { walletId: group.wallet!.id, amount, type: 'CONTRIBUTION', status: 'SUCCESS', reference: `${referenceBase}_CREDIT`, description: `Offline Sync: Received from ${user?.firstName}` }
      });
      // Update Group Total
      await tx.group.update({ where: { id: groupId }, data: { totalContributions: { increment: amount } } });
      // Create Receipt
      await tx.contribution.create({
        data: { userId, groupId, amount, status: 'CONFIRMED', paidAt: new Date() }
      });
    });

    // 4. Fire WebSockets to update the mobile UI instantly!
    const message = `${user?.firstName} ${user?.lastName}'s offline contribution of ₦${amount} just synced! 🎉`;
    await groupService.logAndBroadcast(groupId, 'CONTRIBUTION', message, userId);

    logger.info({ offlineId, userId }, 'Offline contribution synced perfectly');

  } catch (error: any) {
    logger.error(
      { err: error.message, offlineId, attempt: job.attemptsMade + 1 }, 
      `Sync job failed. Retrying in background...`
    );
    
    // 👉 3. CRITICAL: You MUST throw the error, otherwise Bull won't retry!
    // If we reach the final attempt, log a fatal error (You could trigger an email to yourself here)
    if (job.attemptsMade >= 4) {
      logger.fatal({ offlineId }, '🚨 SYNC JOB FAILED PERMANENTLY AFTER 5 ATTEMPTS');
    }
    
    throw error; 
  }
});