import React, { useState } from 'react';
import { View, Text, StyleSheet, SafeAreaView, TouchableOpacity, TextInput, KeyboardAvoidingView, Platform, useColorScheme } from 'react-native';
import { useRouter } from 'expo-router';
import { FontAwesome5, Feather, MaterialCommunityIcons } from '@expo/vector-icons';
import { Colors } from '@/theme/Colors';
import { api } from '@/api/client';

export default function TwoFactorVerifyScreen() {
  const router = useRouter();
  const colorScheme = useColorScheme();
  const theme = colorScheme === 'dark' ? Colors.dark : Colors.light;

  const [code, setCode] = useState(['', '', '', '', '', '']); // 6 digit OTP

  const handleVerify = async () => {
    try {
      const otpString = code.join('');
      await api.post('/auth/2fa/enable', { code: otpString });
      alert('2FA Enabled Successfully!');
      router.replace('/sub/profile/security');
    } catch (e) {
      alert("Invalid Code");
    }
  };

  return (
    <SafeAreaView style={[styles.safeArea, { backgroundColor: theme.background }]}>
      <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
            <FontAwesome5 name="arrow-left" size={18} color={theme.primary} />
          </TouchableOpacity>
          <Text style={[styles.headerTitle, { color: theme.text }]}>2FA Verification</Text>
          <FontAwesome5 name="shield-alt" size={18} color={theme.textSecondary} />
        </View>

        <View style={styles.content}>
          <View style={styles.iconWrapper}>
            <View style={[styles.iconGlow, { backgroundColor: theme.inputBg }]}>
              <MaterialCommunityIcons name="cellphone-key" size={32} color={theme.primary} />
            </View>
          </View>

          <Text style={[styles.title, { color: theme.text }]}>Enter OTP Code</Text>
          <Text style={[styles.subtitle, { color: theme.textSecondary }]}>
            Enter the 6-digit code generated by your authenticator app to secure your QuickSave account.
          </Text>

          {/* 6-Digit OTP Input Boxes */}
          <View style={styles.otpContainer}>
            {code.map((digit, index) => (
              <TextInput
                key={index}
                style={[styles.otpBox, { backgroundColor: theme.inputBg, borderColor: theme.inputBorder, color: theme.text }]}
                maxLength={1}
                keyboardType="number-pad"
                value={digit}
              />
            ))}
          </View>

          <View style={styles.timerContainer}>
            <Feather name="clock" size={14} color={theme.textSecondary} />
            <Text style={[styles.timerText, { color: theme.textSecondary }]}>Resend code in 0:58</Text>
          </View>
          <TouchableOpacity><Text style={[styles.resendText, { color: theme.textSecondary }]}>Didn't receive a code?</Text></TouchableOpacity>
        </View>

        <View style={styles.footer}>
          <TouchableOpacity 
            style={[styles.primaryButton, { backgroundColor: theme.primary }]}
            onPress={handleVerify}
          >
            <Text style={styles.primaryButtonText}>Verify & Enable</Text>
            <Feather name="lock" size={16} color="#111" style={{ marginLeft: 8 }} />
          </TouchableOpacity>
          
          <Text style={[styles.securityNote, { color: theme.textSecondary, marginTop: 20 }]}>
            ENCRYPTED WITH AES-256 PROTOCOL
          </Text>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

// STYLES FOR BOTH SCREENS
const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 15 },
  backButton: { padding: 5 },
  headerTitle: { fontSize: 16, fontWeight: 'bold' },
  content: { flex: 1, paddingHorizontal: 24, paddingTop: 30, alignItems: 'center' },
  iconWrapper: { marginBottom: 20 },
  iconGlow: { width: 70, height: 70, borderRadius: 35, justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 22, fontWeight: 'bold', marginBottom: 12, textAlign: 'center' },
  subtitle: { fontSize: 14, textAlign: 'center', lineHeight: 22, marginBottom: 32, paddingHorizontal: 10 },
  
  optionCard: { flexDirection: 'row', width: '100%', padding: 16, borderRadius: 16, borderWidth: 1, marginBottom: 16, alignItems: 'center' },
  optionIcon: { marginRight: 16 },
  optionTextContainer: { flex: 1 },
  optionTitle: { fontSize: 15, fontWeight: 'bold', marginBottom: 4 },
  recommendedBadge: { backgroundColor: '#FF8C0020', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  recommendedText: { color: '#FF8C00', fontSize: 8, fontWeight: 'bold' },
  optionDesc: { fontSize: 12, lineHeight: 18 },
  radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#555', justifyContent: 'center', alignItems: 'center' },
  radioFill: { width: 10, height: 10, borderRadius: 5 },

  otpContainer: { flexDirection: 'row', justifyContent: 'space-between', width: '100%', marginBottom: 30 },
  otpBox: { width: 45, height: 55, borderWidth: 1, borderRadius: 8, fontSize: 20, textAlign: 'center', fontWeight: 'bold' },
  timerContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, marginBottom: 16 },
  timerText: { fontSize: 13 },
  resendText: { fontSize: 13, fontWeight: '600' },

  footer: { paddingHorizontal: 24, paddingBottom: 32 },
  primaryButton: { flexDirection: 'row', height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center' },
  primaryButtonText: { color: '#111', fontSize: 16, fontWeight: 'bold' },
  securityNote: { textAlign: 'center', fontSize: 10, fontWeight: 'bold', letterSpacing: 1 },
});